'use client';

import { useState } from 'react';
import { Label } from '@/components/ui/label';
import { Input } from '@/components/ui/input';
import { VideoUploader } from '@/components/instructor/VideoUploader';
import type { ILessonContent } from '@/types';

interface Props {
  content?: ILessonContent;
  onChange: (content: Partial<ILessonContent>) => void;
}

/** Form for video-type lessons: uploader + HLS URL + duration display. */
export function VideoLessonForm({ content, onChange }: Props): JSX.Element {
  const [hlsUrl, setHlsUrl] = useState(content?.videoUrl ?? '');

  const handleUploadComplete = (result: { url: string; hlsUrl?: string; duration?: number }): void => {
    const videoUrl = result.hlsUrl ?? result.url;
    setHlsUrl(videoUrl);
    onChange({ videoUrl, duration: result.duration });
  };

  return (
    <div className="space-y-4">
      <VideoUploader onComplete={handleUploadComplete} />

      <div>
        <Label htmlFor="videoUrl">HLS Stream URL (auto-filled after upload)</Label>
        <Input
          id="videoUrl"
          type="url"
          value={hlsUrl}
          onChange={(e) => { setHlsUrl(e.target.value); onChange({ videoUrl: e.target.value }); }}
          placeholder="https://res.cloudinary.com/…/sp_full_hd/m3u8"
        />
        <p className="mt-1 text-xs text-muted-foreground">
          The HLS URL is generated by Cloudinary after your upload processes (~2 min for HD videos).
        </p>
      </div>

      {content?.duration && content.duration > 0 && (
        <p className="text-sm text-muted-foreground">
          Duration: {Math.floor(content.duration / 60)}m {Math.round(content.duration % 60)}s
        </p>
      )}
    </div>
  );
}
