/* eslint-disable no-console */
import { promises as fs } from 'fs';
import path from 'path';

/**
 * API documentation generator.
 *
 * Parses the assembled v1 route tree from source (mount prefixes in
 * `routes/v1/index.ts` + per-file `router.<method>(...)` declarations) and emits
 * a grouped Markdown reference to `docs/API.md`. Source-based parsing keeps it
 * decoupled from Express internals and deterministic.
 *
 * Run with: `npm run docs:api`
 */

const ROUTES_DIR = path.resolve(__dirname, '../routes/v1');
const OUTPUT = path.resolve(__dirname, '../../../docs/API.md');
const API_BASE = '/api/v1';

interface Endpoint {
  method: string;
  routePath: string;
  auth: string;
  validated: boolean;
}

interface Group {
  prefix: string;
  file: string;
  endpoints: Endpoint[];
}

const METHODS = ['get', 'post', 'put', 'patch', 'delete'];

/** Extracts `router.use('<prefix>', <ident>)` mounts + their import sources. */
async function parseIndex(): Promise<{ prefix: string; file: string }[]> {
  const src = await fs.readFile(path.join(ROUTES_DIR, 'index.ts'), 'utf8');

  const imports = new Map<string, string>(); // ident -> file (without extension)
  const importRe = /import\s+(\w+)\s+from\s+'\.\/([\w.]+)'/g;
  for (let m = importRe.exec(src); m; m = importRe.exec(src)) {
    imports.set(m[1], m[2]);
  }

  const mounts: { prefix: string; file: string }[] = [];
  const useRe = /router\.use\(\s*'([^']+)'\s*,\s*(\w+)\s*\)/g;
  for (let m = useRe.exec(src); m; m = useRe.exec(src)) {
    const file = imports.get(m[2]);
    if (file) mounts.push({ prefix: m[1], file });
  }
  return mounts;
}

/** Detects the auth posture annotated on a route declaration line/block. */
function detectAuth(segment: string): string {
  const roleMatch = segment.match(/requireRole\(([^)]*)\)/);
  if (roleMatch) {
    const roles = roleMatch[1].replace(/['"\s]/g, '');
    return `Roles: ${roles}`;
  }
  if (/\bauthenticate\b/.test(segment)) return 'Authenticated';
  if (/\btenantResolver\b/.test(segment)) return 'Public (tenant-scoped)';
  return 'Public';
}

/** Parses a single route file into endpoints. */
async function parseRouteFile(file: string): Promise<Endpoint[]> {
  const full = path.join(ROUTES_DIR, `${file}.ts`);
  const src = await fs.readFile(full, 'utf8');

  // Router-level middleware (router.use(authenticate, requireRole(...))) applies
  // to every route in the file.
  const baseUseRe = /router\.use\(((?:(?!\)\s*;).)*)\)/gs;
  let baseAuth = '';
  for (let m = baseUseRe.exec(src); m; m = baseUseRe.exec(src)) {
    if (!/^\s*'/.test(m[1])) {
      const detected = detectAuth(m[1]);
      if (detected !== 'Public') baseAuth = detected;
    }
  }

  const endpoints: Endpoint[] = [];
  const methodRe = new RegExp(
    `router\\.(${METHODS.join('|')})\\(\\s*'([^']*)'([\\s\\S]*?)\\)\\s*;`,
    'g',
  );
  for (let m = methodRe.exec(src); m; m = methodRe.exec(src)) {
    const [, method, routePath, rest] = m;
    const lineAuth = detectAuth(rest);
    endpoints.push({
      method: method.toUpperCase(),
      routePath,
      auth: lineAuth !== 'Public' ? lineAuth : baseAuth || 'Public',
      validated: /\bvalidate\(/.test(rest),
    });
  }
  return endpoints;
}

function joinPath(prefix: string, routePath: string): string {
  const p = `${API_BASE}${prefix}${routePath === '/' ? '' : routePath}`;
  return p.replace(/\/+$/, '') || API_BASE;
}

function titleFromPrefix(prefix: string): string {
  const name = prefix.replace(/^\//, '').split('/')[0] || 'root';
  return name.charAt(0).toUpperCase() + name.slice(1);
}

async function main(): Promise<void> {
  const mounts = await parseIndex();

  const groups: Group[] = [];
  for (const mount of mounts) {
    try {
      const endpoints = await parseRouteFile(mount.file);
      if (endpoints.length) groups.push({ ...mount, endpoints });
    } catch {
      // Skip files that can't be read.
    }
  }

  const total = groups.reduce((n, g) => n + g.endpoints.length, 0);
  const now = new Date().toISOString().slice(0, 10);

  const lines: string[] = [
    '# NextLearn — API Reference',
    '',
    '> Auto-generated by `npm run docs:api`. Do not edit by hand.',
    '',
    `Generated: ${now} · Base URL: \`${API_BASE}\` · ${total} endpoints across ${groups.length} groups.`,
    '',
    '## Conventions',
    '',
    '- All responses use the envelope `{ success, message, data?, meta? }`.',
    '- Authenticated routes require `Authorization: Bearer <accessToken>`.',
    '- Tenant context comes from the JWT (authenticated) or the `x-tenant-id` header / subdomain (public).',
    '- Paginated list endpoints accept `?page=&limit=` and return `meta` with pagination info.',
    '',
    '## Table of contents',
    '',
    ...groups
      .slice()
      .sort((a, b) => a.prefix.localeCompare(b.prefix))
      .map((g) => `- [${titleFromPrefix(g.prefix)} (\`${g.prefix}\`)](#${titleFromPrefix(g.prefix).toLowerCase()})`),
    '',
  ];

  for (const g of groups.slice().sort((a, b) => a.prefix.localeCompare(b.prefix))) {
    lines.push(`## ${titleFromPrefix(g.prefix)}`, '', `Mounted at \`${API_BASE}${g.prefix}\` · source: \`routes/v1/${g.file}.ts\``, '');
    lines.push('| Method | Path | Access | Body validated |', '| --- | --- | --- | --- |');
    for (const e of g.endpoints) {
      lines.push(
        `| \`${e.method}\` | \`${joinPath(g.prefix, e.routePath)}\` | ${e.auth} | ${e.validated ? 'Yes' : '—'} |`,
      );
    }
    lines.push('');
  }

  await fs.mkdir(path.dirname(OUTPUT), { recursive: true });
  await fs.writeFile(OUTPUT, lines.join('\n'), 'utf8');
  console.log(`Generated ${OUTPUT} — ${total} endpoints across ${groups.length} groups.`);
}

main().catch((err) => {
  console.error('Doc generation failed:', err);
  process.exit(1);
});
